name: expenses_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  persistent_bottom_nav_bar_v2: ^6.2.0
  font_awesome_flutter: ^10.12.0
  fl_chart: ^1.1.1
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  firebase_core: ^4.2.1
  uuid: ^4.5.2

  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  expense_repository:
    path: packages/expense_repository


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
